name: log430-a25-labo0

on:
  push:
    branches: [main, master]
    
jobs:
  test:
    runs-on: self-hosted
    environment: Labo0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: src
        run:  python3 -m pytest 

      - name: Build Docker image
        run: docker build -t labo0-calculator .

      - name: Run Docker-container
        run: |
          docker stop labo0-calculator || true # ensures that the overall command still exits successfully and the script does not stop.
          docker rm labo0-calculator || true
          docker run -d --restart unless-stopped --name labo0-calculator labo0-calculator
